using System;
using System.Collections.Generic;
using BackendCode.Models;

namespace BackendCode
{
    public class Flight
    {
        public static List<FlightDataModel> AircraftAlpha = new List<FlightDataModel> //MCO -> JFK, Total Distance: 1,101 Miles, totalFuel: 6,875 US gal, emergency status: 0
        { 
            {
                phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 0,
                altitude = 0,
                totalDistance = 1101.0,
                remainingDistance = 1101.0,
                pressure = 14.7,
                temperture = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 6875.0,
                fuelBurn = 0,
                origin = "MCO",
                destination = "JFK",
                time = 0,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 5.25,
                altitude = 7500,
                totalDistance = 1101.0,
                remainingDistance = 1046.0,
                pressure = 11.0,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 6548,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 11,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 10.5,
                altitude = 15000,
                totalDistance = 1101.0,
                remainingDistance = 991,
                pressure = 11.0,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 6221,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 22,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 15.75,
                altitude = 22500,
                totalDistance = 1101.0,
                remainingDistance = 936,
                pressure = 5.7,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 5894,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 33,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 21,
                altitude = 30000,
                totalDistance = 1101.0,
                remainingDistance = 881,
                pressure = 4.4,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 5567,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 44,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21,
                altitude = 30000,
                totalDistance = 1101.0,
                remainingDistance = 776,
                pressure = 4.4,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 5240,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 55,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21,
                altitude = 30000,
                totalDistance = 1101.0,
                remainingDistance = 671,
                pressure = 4.4,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 4913,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 66,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21,
                altitude = 30000,
                totalDistance = 1101.0,
                remainingDistance = 566,
                pressure = 4.4,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 4586,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 77,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21,
                altitude = 30000,
                totalDistance = 1101.0,
                remainingDistance = 461,
                pressure = 4.4,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 4259,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 88,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21,
                altitude = 30000,
                totalDistance = 1101.0,
                remainingDistance = 356,
                pressure = 4.4,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 3932,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 99,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 2,
                aircraftType = "Boeing 737-800",
                velocity = 15.75,
                altitude = 22500,
                totalDistance = 1101.0,
                remainingDistance = 267,
                pressure = 6.0,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 3605,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 110,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 2,
                aircraftType = "Boeing 737-800",
                velocity = 10.5,
                altitude = 15000,
                totalDistance = 1101.0,
                remainingDistance = 178,
                pressure = 8,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 3278,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 121,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 2,
                aircraftType = "Boeing 737-800",
                velocity = 5.25,
                altitude = 7500,
                totalDistance = 1101.0,
                remainingDistance = 89,
                pressure = 11.0,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 2951,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 132,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            },
            {
                phase = 2,
                aircraftType = "Boeing 737-800",
                velocity = 0,
                altitude = 0,
                totalDistance = 1101.0,
                remainingDistance = 0,
                pressure = 14.7,
                temperature = 59.0,
                totalFuel = 6875.0,
                remainingFuel = 2624,
                fuelBurn = 327,
                origin = "MCO",
                destination = "JFK",
                time = 143,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 0
            }

        };
        
        public static List<FlightDataModel> AircraftBravo = new List<FlightDataModel> //DFW -> SEA, Total Distance: 2,091.8 Miles, totalFuel: 7,930 US gal, emergency status: 1
        {
            {//pressue but done
                 phase = 0,
                 aircraftType = "Airbus a321",
                 velocity = 0,
                 altitude = 0,
                 totalDistance = 2091.8,
                 remainingDistance = 2091.8,
                 pressure = 14.7,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 7930,
                 fuelBurn = 0,
                 origin = "DFW",
                 destination = "SEA",
                 time = 0,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }, 
             {//done
                 phase = 0,
                 aircraftType = "Airbus a321",
                 velocity = 5.7,
                 altitude = 7500,
                 totalDistance = 2091.8,
                 remainingDistance = 1987.21,
                 pressure = 10.9,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 7638.5,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 27.2,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             },
             {//done
                 phase = 0,
                 aircraftType = "Airbus a321",
                 velocity = 11.4,
                 altitude = 15000,
                 totalDistance = 2091.8,
                 remainingDistance = 1882.62,
                 pressure = 8.0,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 7347,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 54.4,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             },
             {//done
                 phase = 0,
                 aircraftType = "Airbus a321",
                 velocity = 16.1,
                 altitude = 22500,
                 totalDistance = 2091.8,
                 remainingDistance = 1778.03,
                 pressure = 6.2,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 7055.5,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 81.6,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
             {//done
                 phase = 0,
                 aircraftType = "Airbus a321",
                 velocity = 21.8,
                 altitude = 30000,
                 totalDistance = 2091.8,
                 remainingDistance = 1673.44,
                 pressure = 4.4,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 6764,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 108.8,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
             {//done
                 phase = 1,
                 aircraftType = "Airbus a321",
                 velocity = 21.8,
                 altitude = 30000,
                 totalDistance = 2091.8,
                 remainingDistance = 1422.424,
                 pressure = 4.4,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 6472.5,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 136,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
             {//done
                 phase = 1,
                 aircraftType = "Airbus a321",
                 velocity = 21.8,
                 altitude = 30000,
                 totalDistance = 2091.8,
                 remainingDistance = 1171.408,
                 pressure = 4.4,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 6181,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 163.2,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
             {//done
                 phase = 1,
                 aircraftType = "Airbus a321",
                 velocity = 21.8,
                 altitude = 30000,
                 totalDistance = 2091.8,
                 remainingDistance = 920.392,
                 pressure = 4.4,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 5889.5,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 190.4,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
            {//done
                 phase = 1,
                 aircraftType = "Airbus a321",
                 velocity = 21.8,
                 altitude = 30000,
                 totalDistance = 2091.8,
                 remainingDistance = 669.376,
                 pressure = 4.4,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 5598,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 217.6,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
            {//done
                 phase = 1,
                 aircraftType = "Airbus a321",
                 velocity = 21.8,
                 altitude = 30000,
                 totalDistance = 2091.8,
                 remainingDistance = 418.36,
                 pressure = 14.7,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 5306.5,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 244.8,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
            {//done
                 phase = 2,
                 aircraftType = "Airbus a321",
                 velocity = 16.1,
                 altitude = 22500,
                 totalDistance = 2091.8,
                 remainingDistance = 313.77,
                 pressure = 6.2,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 5015,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 272,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
            {//done
                 phase = 2,
                 aircraftType = "Airbus a321",
                 velocity = 10.4,
                 altitude = 15000,
                 totalDistance = 2091.8,
                 remainingDistance = 209.18,
                 pressure = 8.0,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 4723.5,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 299.2,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
            {//done
                 phase = 2,
                 aircraftType = "Airbus a321",
                 velocity = 5.7,
                 altitude = 7500,
                 totalDistance = 2091.8,
                 remainingDistance = 104.59,
                 pressure = 10.9,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 4432,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 326.4,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
            {//done
                 phase = 2,
                 aircraftType = "Airbus a321",
                 velocity = 0,
                 altitude = 0,
                 totalDistance = 2091.8,
                 remainingDistance = 0,
                 pressure = 14.7,
                 temperature = 59,
                 totalFuel = 7930,
                 remainingFuel = 4140.5,
                 fuelBurn = 291.5,
                 origin = "DFW",
                 destination = "SEA",
                 time = 353.6,
                 weight = 106900,
                 leftEngine = true,
                 rightEngine = true,
                 emergency = 0
             }
        };
    
        public static List<FlightDataModel> AircraftCharlie = new List<FlightDataModel> //LAX -> MCI, Total Distance: 1,641.1 Miles, totalFuel: 6,875 US gal, emergency status: 1
        {
            { //done
                phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 0,
                altitude = 0,
                totalDistance = 1641.1,
                remainingDistance = 1641.1,
                pressure = 14.7,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 0,
                fuelBurn = 0,
                origin = "LAX",
                destination = "MCI",
                time = 0,
                weight = 0,
                leftEngine = true,
                rightEngine = true,
                emergency = 1,               
            },
            { //done
                phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 5.4,
                altitude = 7500.0,
                totalDistance = 1641.1,
                time = 14,
                remainingDistance = 1558,
                pressure = 10.9,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 6550,
                fuelBurn = 327,
                origin = LAX,
                destination = MCI,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 1, 
            },
                { //done
                phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 10.8,
                altitude = 15000,
                totalDistance = 1641.1,
                time = 28,
                remainingDistance = 1476,
                pressure = 8.0,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 6223,
                fuelBurn = 327,
                origin = LAX,
                destination = MCI,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 1, 
            },
    { 
            phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 16.2,
                altitude = 22500,
                totalDistance = 1641.1,
                time = 54,
                remainingDistance = 1394,
                pressure = 6.2,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 5896,
                fuelBurn = 327,
                origin = LAX,
                destination = MCI,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 1,

    },
    { //done
               phase = 0,
                aircraftType = "Boeing 737-800",
                velocity = 21.6,
                altitude = 30000,
                totalDistance = 1641.1,
                time = 68,
                remainingDistance = 1311,
                pressure = 4.4,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 5569,
                fuelBurn = 327,
                origin = LAX,
                destination = MCI,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 1,

    },
    { //done
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21.6,
                altitude = 30000,
                totalDistance = 1641.1,
                time = 82,
                remainingDistance = 1115,
                pressure = 4.4,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 5242,
                fuelBurn = 327,
                origin = LAX,
                destination = MCI,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 1,

    },//done
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21.6,
                altitude = 30000,
                totalDistance = 1641.1,
                time = 98,
                remainingDistance = 918,
                pressure = 4.4,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 4915,
                fuelBurn = 327,
                origin = LAX,
                destination = MCI,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 1,

    },
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21.6,
                altitude = 30000,
                totalDistance = 1641.1,
                time = 114,
                remainingDistance = 721,
                pressure = 4.4,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 4588,
                fuelBurn = 327,
                origin = LAX,
                destination = MCI,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 1,

    },
    { //done
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21.6,
                altitude = 30000,
                totalDistance = 1641.1,
                time = 128,
                remainingDistance = 721,
                pressure = 4.4,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 4261,
                fuelBurn = 327,
                origin = LAX,
                destination = MCI,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 1,
    },
    { //done
                phase = 1,
                aircraftType = "Boeing 737-800",
                velocity = 21.6,
                altitude = 30000,
                totalDistance = 1641.1,
                time = 142,
                remainingDistance = 524,
                pressure = 4.4,
                temperature = 59,
                totalFuel = 6875,
                remainingFuel = 4588,
                fuelBurn = 327,
                origin = LAX,
                destination = MCI,
                weight = 90710,
                leftEngine = true,
                rightEngine = true,
                emergency = 1,
    }
    }
    
}